export const INVENTORY_INDEX = 'INVENTORY_ITEMS_INDEX';
export const INVENTORY_INDEX_SUCCESS = 'INVENTORY_ITEMS_INDEX_SUCCESS';
export const INVENTORY_INDEX_FAILURE = 'INVENTORY_ITEMS_INDEX_FAILURE';

export const BILL_ADD_OR_UPDATE = 'BILL_ADD_OR_UPDATE';
export const BILL_REMOVE = 'BILL_REMOVE';
export const BILL_UPDATE_SUCCESS = 'BILL_UPDATE_SUCCESS';

export const KEYPAD_UPDATE = 'KEYPAD_UPDATE';
export const KEYPAD_SET_POINT = 'KEYPAD_SET_POINT';
export const KEYPAD_CLEAR = 'KEYPAD_CLEAR';
